// <auto-generated />
using System;
using MeetingApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingApp.Infrastructure.Migrations
{
    [DbContext(typeof(MeetingDbContext))]
    [Migration("20260407134119_Final Migration")]
    partial class FinalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MeetingApp.Domain.Moderators.ColleagueRecord", b =>
                {
                    b.Property<Guid>("EntraObjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyAdded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModerationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePictureUri")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("EntraObjectId");

                    b.HasIndex("Email");

                    b.HasIndex("Department", "IsActive");

                    b.ToTable("Colleagues");
                });
#pragma warning restore 612, 618
        }
    }
}
